$ErrorActionPreference = "Stop"

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
& (Join-Path $root "Windows\build-win.ps1")

$codexDir = Join-Path $env:USERPROFILE ".codex"
$bin = Join-Path $codexDir "bin"
New-Item -ItemType Directory -Force -Path $bin | Out-Null
Copy-Item -Force (Join-Path $root "dist\windows\codex-light-mxp.exe") (Join-Path $bin "codex-light-mxp.exe")
Copy-Item -Force (Join-Path $root "dist\windows\codex-light-hook-mxp.exe") (Join-Path $bin "codex-light-hook-mxp.exe")
Write-Output "Installed commands to $bin"

New-Item -ItemType Directory -Force -Path $codexDir | Out-Null
$configPath = Join-Path $codexDir "config.toml"
$hookExe = Join-Path $bin "codex-light-hook-mxp.exe"
$tomlHookExe = $hookExe.Replace("\", "\\")
$begin = "# BEGIN Codex Traffic Light MXP Windows hooks"
$end = "# END Codex Traffic Light MXP Windows hooks"
$hookBlock = @"
$begin
# Generated by Windows\install-global-command-win.ps1. Re-run the installer to update paths.
# After installing, run /hooks in Codex and trust these hooks.

[[hooks.UserPromptSubmit]]
[[hooks.UserPromptSubmit.hooks]]
type = "command"
command = "$tomlHookExe UserPromptSubmit"
timeout = 5
statusMessage = "Codex traffic light: working"

[[hooks.PreToolUse]]
matcher = ".*"
[[hooks.PreToolUse.hooks]]
type = "command"
command = "$tomlHookExe PreToolUse"
timeout = 5
statusMessage = "Codex traffic light: working"

[[hooks.PermissionRequest]]
matcher = ".*"
[[hooks.PermissionRequest.hooks]]
type = "command"
command = "$tomlHookExe PermissionRequest"
timeout = 5
statusMessage = "Codex traffic light: waiting"

[[hooks.Stop]]
[[hooks.Stop.hooks]]
type = "command"
command = "$tomlHookExe Stop"
timeout = 5
statusMessage = "Codex traffic light: done"

[[hooks.SubagentStop]]
matcher = ".*"
[[hooks.SubagentStop.hooks]]
type = "command"
command = "$tomlHookExe SubagentStop"
timeout = 5
statusMessage = "Codex traffic light: subagent done"
$end
"@

$existing = ""
if (Test-Path $configPath) {
  $existing = Get-Content -Raw -LiteralPath $configPath
  $backupPath = "$configPath.bak-codex-light-win-$(Get-Date -Format yyyyMMddHHmmss)"
  Copy-Item -LiteralPath $configPath -Destination $backupPath -Force
  Write-Output "Backed up Codex config to $backupPath"
}

$pattern = "(?s)# BEGIN Codex Traffic Light MXP Windows hooks.*?# END Codex Traffic Light MXP Windows hooks\s*"
if ([regex]::IsMatch($existing, $pattern)) {
  $updated = [regex]::Replace($existing, $pattern, $hookBlock + "`r`n")
} elseif ([string]::IsNullOrWhiteSpace($existing)) {
  $updated = $hookBlock + "`r`n"
} else {
  $updated = $existing.TrimEnd() + "`r`n`r`n" + $hookBlock + "`r`n"
}

Set-Content -LiteralPath $configPath -Value $updated -Encoding UTF8
Write-Output "Installed Codex hooks to $configPath"
Write-Output "Next step: open Codex, run /hooks, then trust the Codex Traffic Light hooks."
